// src/components/menu/NavBar.vue
<template>
    <div
        :class="[
            'md:hidden fixed left-5 w-12 h-12 rounded-full flex items-center justify-center',
            'bg-white/60 border border-slate-100/70 dark:border-slate-700dark:bg-slate-700/60 backdrop-blur-xl z-[9999] transition-all bottom-6'
        ]"
        @click="openMenu = !openMenu"
    >
        <Transition name="toggle-menu">
            <i class="ph-light ph-list text-3xl z-50 text-slate-900 dark:text-white absolute" v-if="!openMenu"></i>
            <i class="ph-light ph-x text-3xl z-50 text-slate-900 dark:text-white absolute" v-else></i>
        </Transition>
    </div>

    <Transition name="toggle-menu" @after-enter="retrieveCurrent">
        <nav
            v-show="openMenu || noResponsive"
            id="mainMenu"
            :class="[
                'fixed z-[9999] bottom-20 m-auto backdrop-blur-xl p-2 rounded-xl md:rounded-[50px] shadow-sm',
                'bg-white/60 border border-slate-100/70 dark:border-slate-700 dark:bg-slate-700/60 transition-all md:bottom-10',
                'md:motion-translate-y-in-[150px] md:motion-scale-in-0 md:motion-blur-in md:motion-delay-500 motion-duration-300'
            ]"
        >
            <div
                class="bg-slate-900 dark:bg-slate-300 rounded-xl md:rounded-[45px] absolute transition-all duration-300"
                :style="{
                    left: currentLeft,
                    width: currentWidth,
                    top: currentTop,
                    height: `${clientHeight}px`
                }"
            ></div>
            <ul class="md:flex gap-5 justify-between">
                <MenuItem
                    v-for="page in localPages"
                    :name="page.name"
                    :current="page.current"
                    :key="page.path"
                    :path="page.path"
                    :special="page.specialLink"
                    @followItem="($e) => handleHover($e)"
                    @hoverStop="retrieveCurrent()"
                    @active-page-change="($e) => changeActivePage($e)"
                />
            </ul>
        </nav>
    </Transition>
</template>

<script>
import MenuItem from './MenuItem.vue'

const localSelectors = {
    menuListItem: '#mainMenu ul li',
    currenItem: '#mainMenu ul li.current-item'
}

export default {
    components: {
        MenuItem
    },
    data() {
        return {
            currentLeft: 0,
            currentTop: 0,
            currentWidth: '50px',
            openMenu: false,
            clientHeight: 0,
            localPages: this.pages
        }
    },
    mounted() {
        this.clientHeight = document.querySelector(localSelectors.menuListItem).clientHeight
        this.retrieveCurrent()
    },
    watch: {
        '$i18n.locale'() {
            setTimeout(() => {
                this.currentWidth = `${this.getCurrentItem()?.clientWidth}px`
                this.currentLeft = `${this.getCurrentItem()?.offsetLeft}px`
            }, 50)
        }
    },
    computed: {
        noResponsive() {
            return window.innerWidth >= 768
        }
    },
    props: ['pages'],
    methods: {
        handleHover(e) {
            this.moveTracker(e.$refs.listItem)

            this.getCurrentItem().classList.remove(['text-white'])
            this.getCurrentItem().classList.add(['text-slate-900', 'dark:text-slate-200'])
        },
        retrieveCurrent() {
            this.moveTracker(this.getCurrentItem())
            this.getCurrentItem().classList.add(['text-white'])
            this.getCurrentItem().classList.remove(['text-slate-900', 'dark:text-slate-200'])
        },
        moveTracker(element) {
            this.currentLeft = `${element.offsetLeft}px`
            this.currentWidth = `${element.clientWidth}px`
            this.currentTop = `${element.offsetTop}px`
            this.clientHeight = element.clientHeight
        },
        changeActivePage(e) {
            this.localPages.forEach((element) => {
                element.current = element.path === e.$refs.link.to
            })
        },
        getCurrentItem() {
            return document.querySelector(localSelectors.currenItem)
        }
    }
}
</script>

<style>
.toggle-menu-enter-active,
.toggle-menu-leave-active {
    transition: all 0.25s ease-out;
}
.toggle-menu-enter-from {
    opacity: 0;
    transform: translateY(30px);
}
.toggle-menu-leave-to {
    opacity: 0;
    transform: translateY(-30px);
}
</style>

// next/src/components/menu/NavBar.tsx
"use client"

import {ReactElement, useState} from "react";
import {NavItem} from "@/src/types/menu";
import MenuItem from "@/src/components/menu/MenuItem";

const LOCAL_SELECTORS = {
    menuListItem: '#mainMenu ul li',
    currenItem: '#mainMenu ul li.current-item'
}

export default function NavBar({ pages }: { pages: NavItem[] }): ReactElement {
    const [currentLeft, setCurrentLeft] = useState<string>('0');
    const [currentTop, setCurrentTop] = useState<string>('0');
    const [currentWidth, setCurrentWidth] = useState<string>('50px');
    const [openMenu, setOpenMenu] = useState<boolean>(false);
    const [clientHeight, setClientHeight] = useState<number>(0);
    const [localPages, setLocalPages] = useState<NavItem[]>(pages);

    const noResponsive = window.innerWidth >= 768;

    const handleHover = (e: HTMLElement) => {
        moveTracker(e)

        getCurrentItem().classList.remove('text-white')
        getCurrentItem().classList.add('text-slate-900')
    }

    const retrieveCurrent = () => {
        const current = getCurrentItem()

        if (current) {
            moveTracker(current)
            current.classList.add('text-white')
            current.classList.remove('text-slate-900')
        }
    }

    const moveTracker = (element: HTMLElement) => {
        setCurrentLeft(`${element.offsetLeft}px`)
        setCurrentWidth(`${element.clientWidth}px`)
        setCurrentTop(`${element.offsetTop}px`)
        setClientHeight(element.clientHeight)
    }

    const changeActivePage = (path: string) => {
        const newPages = structuredClone(localPages);
        newPages.forEach((element: NavItem) => {
            element.current = element.path === path
        })

        setLocalPages(newPages);
    }

    const getCurrentItem = (): HTMLElement => {
        return document.querySelector(LOCAL_SELECTORS.currenItem) as HTMLElement
    }

    return (
        <>
            <div
                className={[
                    'md:hidden fixed left-5 w-12 h-12 rounded-full flex items-center justify-center',
                    'bg-white/20 border border-slate-100/20 backdrop-blur-xl backdrop-saturate-200 z-[9999] transition-all bottom-6',
                    'shadow-md'
                ].join(' ')}
                onClick={() => setOpenMenu(prev => !prev)}
            >
                {
                    openMenu
                        ? <i className="ph-light ph-list text-3xl z-50 text-slate-900 dark:text-white absolute"></i>
                        : <i className="ph-light ph-x text-3xl z-50 text-slate-900 dark:text-white absolute"></i>
                }
            </div>
            <nav
                id="mainMenu"
                className={[
                    'fixed z-[9999] bottom-20 m-auto backdrop-blur-xl backdrop-saturate-200 p-2 rounded-xl md:rounded-[50px] shadow-md',
                    'bg-white/20 border border-slate-100/20 transition-all md:bottom-10',
                    'md:motion-translate-y-in-[150px] md:motion-scale-in-0 md:motion-blur-in md:motion-delay-500 motion-duration-300',
                    (openMenu || noResponsive ? '' : 'hidden')
                ].join(' ')}
            >
                <div
                    className="bg-black rounded-xl md:rounded-[45px] absolute transition-all duration-300"
                    style={{
                        left: currentLeft,
                        width: currentWidth,
                        top: currentTop,
                        height: `${clientHeight}px`
                    }}
                ></div>
                <ul className="md:flex gap-5 justify-between">
                    {
                        localPages.map(page => (
                            <MenuItem
                                page={page}
                                key={page.path}
                                onFollowItem={handleHover}
                                onHoverStop={retrieveCurrent}
                                onActiveChange={changeActivePage}
                            />
                        ))
                    }
                </ul>
            </nav>
        </>
    )
}
